# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffer.proto',
  package='buffer',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x62uffer.proto\x12\x06\x62uffer\"\xbb\x01\n\x05\x62oard\x12\x15\n\rcurrent_state\x18\x01 \x03(\x08\x12\x16\n\x0eour_group_lib1\x18\x02 \x03(\x08\x12\x16\n\x0eour_group_lib2\x18\x03 \x03(\x08\x12\x1b\n\x13our_group_lib3_plus\x18\x04 \x03(\x08\x12\x17\n\x0foppo_group_lib1\x18\x05 \x03(\x08\x12\x17\n\x0foppo_group_lib2\x18\x06 \x03(\x08\x12\x1c\n\x14oppo_group_lib3_plus\x18\x07 \x03(\x08\"3\n\x04rank\x12\r\n\x05x_cor\x18\x01 \x03(\x05\x12\r\n\x05y_cor\x18\x02 \x03(\x05\x12\r\n\x05value\x18\x03 \x03(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOARD = _descriptor.Descriptor(
  name='board',
  full_name='buffer.board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_state', full_name='buffer.board.current_state', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib1', full_name='buffer.board.our_group_lib1', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib2', full_name='buffer.board.our_group_lib2', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib3_plus', full_name='buffer.board.our_group_lib3_plus', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib1', full_name='buffer.board.oppo_group_lib1', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib2', full_name='buffer.board.oppo_group_lib2', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib3_plus', full_name='buffer.board.oppo_group_lib3_plus', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=212,
)


_RANK = _descriptor.Descriptor(
  name='rank',
  full_name='buffer.rank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_cor', full_name='buffer.rank.x_cor', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_cor', full_name='buffer.rank.y_cor', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='buffer.rank.value', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['board'] = _BOARD
DESCRIPTOR.message_types_by_name['rank'] = _RANK

board = _reflection.GeneratedProtocolMessageType('board', (_message.Message,), dict(
  DESCRIPTOR = _BOARD,
  __module__ = 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:buffer.board)
  ))
_sym_db.RegisterMessage(board)

rank = _reflection.GeneratedProtocolMessageType('rank', (_message.Message,), dict(
  DESCRIPTOR = _RANK,
  __module__ = 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:buffer.rank)
  ))
_sym_db.RegisterMessage(rank)


# @@protoc_insertion_point(module_scope)
